development:
  adapter: postgresql
  encoding: unicode
  database: smallpolls_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: smallpolls_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: smallpolls_production
  pool: 5
